### ISSUE TITLE
does not work / how to use

### ISSUE THREAD

**Issue by linux-universe** [flathub/org.freedesktop.Platform.VulkanLayer.gamescope#213]
```
username@hostname:~> flatpak run --env=PATH=$PATH:/usr/lib/extensions/vulkan/gamescope/bin com.valvesoftware.Steam 
bwrap: execvp steam: No such file or directory
```

all flatpaks installed via user repo
openSUSE Aeon

**Comment by ColinKinloch** [comment]
The reason steam cannot be found is that `$PATH` will be expanded in the host environment.
Beyond that gamescope should already be in the PATH for the steam flatpak.
Beyond that the reasons it won't work are explored in the other issues in this repo. 😁 😞
