### ISSUE TITLE
transparent game window

### ISSUE THREAD

**Issue by ricc3** [flathub/org.freedesktop.Platform.VulkanLayer.gamescope#220]
Hello
As I am new to the Linux world, I don't know where to look for help anymore.

I have a problem with Steam (installed via flatpak ), gamescope and the game. As far as I can see an older title works without any problem no matter if I use the usual proton or ge . But with the newer one it is not so cool anymore.

Regardless of whether I start the game with the flag _gamescope -f -- %command%_ or _gamescope -- %command%_ I get a sort of transparent game window, and in the steam terminal it loops me a message:

```
[Gamescope WSI] Atom of T was wrong type. Expected XCB_ATOM_CARDINAL.
[Gamescope WSI] Failed to get Xwayland server id. Failing swapchain creation.
[Gamescope WSI] Creating swapchain for xid: 0x7000059 - minImageCount: 3 - format: VK_FORMAT_A2B10G10R10_UNORM_PACK32 - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
```

I tried yet to check if the same error is with the Steam system version but I fell down when compiling because wayland-server 1.21 is required and Pop!_OS only provides 1.20.

Thank you very much for your help as well as any information and apologies for my poor English

**Comment by zastrixarundell** [comment]
Gamescope doesn't work on steam with never versions of proton or without the flatpak of proton. See issue #6.
