### ISSUE TITLE
`--expose-wayland` gives black screen unless `ENABLE_GAMESCOPE_WSI=0`

### ISSUE THREAD

**Issue by Renarde-dev** [flathub/org.freedesktop.Platform.VulkanLayer.gamescope#263]
Using `gamescope --expose-wayland  %command%` as a launch option break video output.
The logs were filled with the same message :
```
[Gamescope WSI] Creating swapchain for xid: 0x5a00070 - minImageCount: 3 - format: VK_FORMAT_R8G8B8A8_UNORM - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
[Gamescope WSI] Atom of T was wrong type. Expected XCB_ATOM_CARDINAL.
[Gamescope WSI] Failed to get Xwayland server id. Failing swapchain creation.
```

OS : Fedora 40
Display server : mutter (Wayland)
Steam version : Flatpak
Gamescope version : Flatpak 23.08
GPU : AMD ( RX 7600)

Adding `ENABLE_GAMESCOPE_WSI=0 gamescope --expose-wayland  %command%` make the problem go away but distort the UI of some games (usually resetting the resolution in game fix the problems ).

**Comment by ColinKinloch** [comment]
This issue isn't specific to the flatpak and has an issue on the upstream repo.
