### ISSUE TITLE
Alert: Gamescope is now fixed

### ISSUE THREAD

**Issue by Arcitec** [flathub/org.freedesktop.Platform.VulkanLayer.gamescope#279]
@ColinKinloch

This issue:
https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/pull/256

Has been fixed 2 days ago:
- https://github.com/ValveSoftware/gamescope/issues/1445#event-15411075548
- https://github.com/ValveSoftware/gamescope/pull/1597

Edit: Oh my god, sorry, you were the person who fixed it. :laughing:

**Comment by ColinKinloch** [comment]
:tada:
