### ISSUE TITLE
New package doesn't work while the old one does

### ISSUE THREAD

**Issue by zastrixarundell** [flathub/org.freedesktop.Platform.VulkanLayer.gamescope#49]
Essentially as per this title.

When I try to install gamescope and use this version of it, it doesn't work. it doesn't recognize `-U` nor can I run a game with `gamescope -- %command%`. 

When I install the deprecated version of gamescope, it works. I am running a 1080p screen so I can't really see any changes from gamescope but at the very least it does allow for my games to launch. 

Is there something which I'm missing? Like a permission which needs to be added to the steam/gamescope flatapk?

I don't really understand the reason why the old package is deprecated while the new one doesn't work at all.

**Comment by orowith2os** [comment]
This package works perfectly fine, it just needs some updates (to the 23.08 branch - 22.08 won't be maintained) and someone to maintain it.  Updating it would probably fix a ton of the problems.

**Comment by zastrixarundell** [comment]
@orowith2os The package does _not_ work fine and that is why I have opened the issue.

It only works with the deprecated version. I have recorded this to showcase the issue. 

I have an 6600XT gpu running fedora kinoite. 

```bash
$ rpm-ostree status 
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-main:latest
                   Digest: sha256:ca623568f0503d9be9495f995898d653f6e241ae351cb9a8059f175ab67e68d8
                  Version: 38.20231021.0 (2023-10-21T07:15:22Z)
      RemovedBasePackages: firefox firefox-langpacks 118.0.2-1.fc38
          LayeredPackages: code corectrl gnome-boxes goverlay krunvm pulseaudio-utils waydroid WoeUSB

```

Of coruse, steam is in a flatpak.

https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/assets/30195425/dbf0811d-d536-4707-bb5d-0dd379fed4ee

**Comment by orowith2os** [comment]
If it doesn't work fine for you, you can help fix it.

**Comment by zastrixarundell** [comment]
I don't know how to code anything with gamescope. That's why I opened an issue which was closed. If I knew how to fix it, I would've opened a PR. Please re-open an issue, as it is, in-fact, an issue.

**Comment by dariox86** [comment]
I'm chiming in to report that I have the same problem. I have yet to dive into the issue to find out what's going on.

**Comment by dariox86** [comment]
Update: issuing the following command fixes the issue for me:
`flatpak update --commit=0b3543a920d07271426945f9ebde207de89232475d6f6ba8bf98ff7cb3f2590e runtime/org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/23.08`
Source: https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/152
